name: Swift

on:
  push:
    branches: [ feat/*, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        pod install --repo-update --clean-install --project-directory=After-iOS/
        xcodebuild test -workspace './After-iOS/After-iOS.xcworkspace' -scheme 'After-iOSTests' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
      
